export const SET_INFO = 'SET_INFO';
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const CLOSE_LOGIN = 'CLOSE_LOGIN';
export const SHOW_REGISTER = 'SHOW_REGISTER';
export const CLOSE_REGISTER = 'CLOSE_REGISTER';
export const ADD_BLOG_CATEGORIES = 'ADD_BLOG_CATEGORIES';
export const ADD_BLOG_TAGS = 'ADD_BLOG_TAGS';